### PR TITLE
Update AdvEx.cpp

### PR DESCRIPTION
**Pull request by BitTheByte**

### CODE REVIEW

**Review by ZodicSlanser — COMMENTED** [review]
On it!

**Comment by BitTheByte** [comment]
@ZodicSlanser Looks like there is no progress done regarding this issue. unfortunately, this means you're going to get banned from cuties club or maybe we can sort this out in some other way 😉

**Comment by ZodicSlanser** [comment]
We apologize for the inconvenience, however we politely decline your nice gesture for we are already seeing someone. 
Thanks for your contribution. 
This issue will now be closed.

**Comment by BitTheByte** [comment]
@ZodicSlanser YOU CAN NOT DECLINE ME I DECLINE YOU!!!

**Comment by BitTheByte** [comment]
@ZodicSlanser HOW YOU DARE! NOW I AM UPSET AND WILL USE MY ULTIMATE WEAPON

**Comment by BitTheByte** [comment]
سونتيانه

**Comment by BitTheByte** [comment]
# سونتيانه

**Comment by BitTheByte** [comment]
## سونتيانه

**Comment by BitTheByte** [comment]
### سونتيانه

**Comment by BitTheByte** [comment]
#### سونتيانه

**Comment by BitTheByte** [comment]
##### سونتيانه

**Comment by BitTheByte** [comment]
###### سونتيانه

**Pull request closed without merging**
